Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
    NewCops: enable