version: 2.1
executors:
  rails:
    docker:
      - image: circleci/ruby:2.6.2-node
        environment:
          RAILS_ENV: test
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/calendar

commands:
  install_bundler:
    steps:
      - run: gem install bundler -v 2.1.4
  restore_modules_server:
    steps:
      - restore_cache:
          key: v1-calendar-{{ .Environment.CIECLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies

jobs:  
  fetch_source_code:
    exector:
      name: rails
    steps:
      - checkout
      - save_cache:
          key: v1-calendar-{{ .Environment.CIECLE_SHA1 }}
          paths:
            - ~/calendar
  bundle_dependencies:
    executor:
      name: rails
    steps:
      - restore_modules_server
      - install_bundler
      - run:
          name: Bundle Install Dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      -save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          path:
            - vendor/bundle
  rspec:
    executor:
      name: rails
    steps:
      - restore_modules_server
      - run:
          name: Waiting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:3306 -timeout 120s
      # Database setup
      - run: mv ./config/database.yml.ci ./config/database.yml
      - install_bundler
      - run:
          name: Testing DB migration and seed
          command: |
            bundle exec rails db:create db:seed db:drop
      - run:
          name: Run rspec
          command: |
            mkdir /tmp/test-results
            mkdir -p ~/rspec
            bundle exec rails db:create db:migrate
            TEST_FILES="$(circleci tests glob \"spec/**/*_spec.rb\" | circleci tests split --split-by=timings)"
            bundle exec rspec --require rails_helper \
                              --color \
                              --format progress \
                              --out ~/rspec/rspec.xml
      # collect reports
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/tem/test-results
          destination: test-results

workflows:
  version: 2
  build_and_test_server:
    jobs:
      - fetch_source_code
      - bundle_dependencies:
          requires:
            - fetch_source_code
      - rspec:
          requires:
            - bundle_dependencies
